INSERT INTO `PRODUCT` (`productName`, `description`, `priceInCHF`, `remainingNumber`) VALUES ("ASUS ROG STRIX GeForce RTX 3070 Ti O8G GAMING (LHR)", "La carte graphique ASUS GeForce ROG STRIX RTX 3070 Ti O8G GAMING embarque 8 Go de mémoire vidéo de nouvelle génération GDDR6X. Ce modèle overclocké d'usine bénéficie de fréquences de fonctionnement élevées et d'un système de refroidissement amélioré gage de fiabilité et de performances à long terme.", "963.95", "67");
INSERT INTO `PRODUCT` (`productName`, `description`, `priceInCHF`, `remainingNumber`) VALUES ("Clavier Gaming mécanique Corsair K60 RGB PRO Noir", "Le clavier mécanique gaming CORSAIR K60 PRO est à la fois stylé et performant avec son châssis en aluminium brossé et ses switchs mécaniques CHERRY VIOLA. Illuminez votre bureau avec un rétroéclairage rouge éclatant par touche renforcé pas une lueur sous touche et ayez l’avantage dans le jeu avec les remappages de touche et les macros personnalisées grâce au logiciel CORSAIR iCUE. Avec le rollover complet des touches et la technologie 100 % anti-ghosting qui garantissent l’enregistrement de vos pressions de touche et le mode de verrouillage de la touche Windows qui empêche l’interruption du jeu, le K60 PRO vous permet d’être le joueur clé.
Châssis en aluminium anodisé : Fabriqué en aluminium brossé et anodisé en noir, il allie un look moderne et élégant et une durabilité prolongée.
Switchs mécaniques 100 % CHERRY VIOLA : Offrent un déplacement linéaire souple et des entrées précises et rapides.
Rétroéclairage à LED rouge par touche : Renforcé pas une lueur sous touche respectant le standard bottom row, ce rétroéclairage éclatant vous permet d’illuminer votre bureau.
Logiciel CORSAIR iCUE: Permet de contrôler l’éclairage, de programmer des macros personnalisées, de remapper les touches et bien plus encore.
100 % Anti-Ghosting avec rollover complet des touches (NKRO) : Assure l’enregistrement de chaque frappe, peu importe la vitesse à laquelle vous jouez.
Mode Verrouillage de la touche Windows : Vous empêche d’interrompre involontairement votre partie à un moment critique.
Raccourcis clavier pratiques : Contrôlez à la volée la lecture média, le volume et l’éclairage embarqué.", "129.95", "43");
INSERT INTO `PICTURE` (`fileName`) VALUES ("LD0005841930_1.jpg");
INSERT INTO `PICTURE` (`fileName`) VALUES ("LD0005841931_1.jpg");
INSERT INTO `PICTURE` (`fileName`) VALUES ("LD0005841932_1.jpg");
INSERT INTO `PICTURE` (`fileName`) VALUES ("LD0005841933_1.jpg");
INSERT INTO `PICTURE` (`fileName`) VALUES ("LD0005841934_1.jpg");
INSERT INTO `PICTURE` (`fileName`) VALUES ("Clavier-Gaming-mecanique-Corsair-K60-RGB-PRO-Noir.jpg");
INSERT INTO `PICTURE` (`fileName`) VALUES ("Clavier-Gaming-mecanique-Corsair-K60-RGB-PRO-Noir2.jpg");
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'ASUS ROG STRIX GeForce RTX 3070 Ti O8G GAMING (LHR)'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'LD0005841930_1.jpg'), 1);
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'ASUS ROG STRIX GeForce RTX 3070 Ti O8G GAMING (LHR)'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'LD0005841931_1.jpg'), 0);
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'ASUS ROG STRIX GeForce RTX 3070 Ti O8G GAMING (LHR)'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'LD0005841932_1.jpg'), 0);
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'ASUS ROG STRIX GeForce RTX 3070 Ti O8G GAMING (LHR)'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'LD0005841933_1.jpg'), 0);
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'ASUS ROG STRIX GeForce RTX 3070 Ti O8G GAMING (LHR)'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'LD0005841934_1.jpg'), 0);
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'Clavier Gaming mécanique Corsair K60 RGB PRO Noir'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'Clavier-Gaming-mecanique-Corsair-K60-RGB-PRO-Noir.jpg'), 1);
INSERT INTO `PICTURE_PRODUCT` (`idProduct`, `idPicture`, `isDefaultPicture`) VALUES ((SELECT `idProduct` FROM `PRODUCT` WHERE `productName` = 'Clavier Gaming mécanique Corsair K60 RGB PRO Noir'), (SELECT `idPicture` FROM `PICTURE` WHERE `fileName` = 'Clavier-Gaming-mecanique-Corsair-K60-RGB-PRO-Noir2.jpg'), 0);